# Generated by Django 4.2.3 on 2023-10-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("prep_time", models.PositiveIntegerField()),
                ("cook_time", models.PositiveIntegerField()),
                ("total_time", models.PositiveIntegerField()),
                ("servings", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="recipe_images/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
                ("website", models.URLField()),
                ("email_address", models.CharField(max_length=100)),
                ("opening_hours", models.CharField(max_length=100)),
            ],
        ),
    ]
