# Generated by Django 4.2.3 on 2023-10-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FoodApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(blank=True, upload_to="restaurant_images/"),
        ),
    ]
