# Generated by Django 4.2.3 on 2023-10-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FoodApp", "0002_restaurant_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Searches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cook_time",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="prep_time",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="servings",
        ),
        migrations.AddField(
            model_name="recipe",
            name="link",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name="recipe",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="reviews",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name="recipe",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="total_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
