# Generated by Django 4.2.3 on 2023-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FoodApp", "0003_searches_remove_recipe_cook_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="total_time",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
